app1/urls.py
from django.urls import path

from app1.views import *

app_name ='app1'

urlpatterns =[
    path('first/',first,name='first'),
]

app2/urls.py
from django.urls import path

from app2.views import *

app_name ='app2'

urlpatterns =[
    path('second/',second,name='second'),
]

project7/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def first(request):
    d={'name':'Sai Reddy','age':23,'location':'kavali'}
    return render(request,'first.htm',d)

app2/views.py
from django.shortcuts import render

# Create your views here.

def second(request):
    d={'name':'sravan','age':24,'location':'ATP'}
    return render(request,'second.html',d)

templates/first.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is an Ong PAge</h1>
        <h1>This is an app1 page</h1>
        <h1>{{name}}</h1><br>
        <h1>{{age}}</h1><br><br>
        <h1>{{location}}</h1><br>


       <h1> <a href="{% url 'app2:second' %}"> Go to ATP Page</a></h1>
    </center>
    
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <title>Seond page</title>
</head>
<body>
    <center>
        <h1>This is an Second app2</h1>
        <h1>This is an ATP</h1>
        <h1>{{name}}</h1><br>
        <h1>{{age}}</h1><br>
        <h1>{{location}}</h1><br>

        <h1><a href="{% url 'app1:first' %}">Go to Kavali page</a></h1>
    </center>
</body>
</html>